fix: success message positioning
getAlby/lightning-browser-extension pull request #1330
Opened 2022-08-24 09:23 UTC by bumi

trying to fix this view
<img width="490" alt="image" src="https://user-images.githubusercontent.com/318/186382068-03a73847-5c9c-40b9-9ed3-3cb53c66d9d2.png">

I guess something like that also needs to be updated on the other views. maybe @im-adithya you can have a look a this?

2022-08-24 10:56 UTC, escapedcat submitted a review, later dismissed

2022-08-24 13:40 UTC, im-adithya requested changes

2022-08-24 14:06 UTC, bumi commented on src/app/screens/LNURLAuth/index.tsx
>          <Container isScreenView maxWidth="sm">
can you make a PR and also check it on the other screens?

2022-08-25 02:21 UTC, escapedcat commented on src/app/screens/LNURLAuth/index.tsx
>          <Container isScreenView maxWidth="sm">
Ah, this was copied from somewhere else and is not a main "screen". Thanks for the comment!
Please have a look once your back :)

2022-09-03 09:47 UTC, escapedcat commented
Resolved via #1365

2022-09-03 09:47 UTC, closed without merging