Use minSendable and maxSendable values from LNURLp response to guide user input
getAlby/lightning-browser-extension pull request #1697
Opened 2022-11-02 09:23 UTC by fanismichalakis

### Describe the changes you have made in this PR

Use the `minSendable`and `maxSendable`fields in the LNURLp response to display better suggestions in the `SatButtons` component, and disable the "Confirm" button if the input amount is out of the [min, max] range.
The values suggested by `SatsButton`still default to 100, 1K, 5K and 10K (current behavior) if the `minSendable`and `maxSendable` are missing or if they are "standard" (eg min below 100 sats and max above 10k sats).

### Link this PR to an issue [optional]

Fixes #1569

### Type of change

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]
![Screenshot 2022-11-02 at 10 00 51](https://user-images.githubusercontent.com/45755277/199452532-9d6c5b10-c507-45f4-9eb5-de169d0e9ff8.png)
![Screenshot 2022-11-02 at 10 00 41](https://user-images.githubusercontent.com/45755277/199452538-3035e078-e234-416d-b450-2c9747138fe0.png)

### How has this been tested?

Tested manually:
- on web pages where `minSendable` and `maxSendable` values are "standard". For example: https://twitter.com/getAlby ;
- on web pages where `minSendable` and `maxSendable` values are a bit more exotic. For example: https://fanismichalakis.fr, where the LN Markets Lightning Address requires a `minSendable` amount of 1000 sats ;
- by changing the code in the LnurlPay component to pass arbitrary values to the `SatButtons`component. For example: `<SatButtons
                            onClick={setValueSat}
                            disabled={loadingConfirm}
                            min={42000}
                            max={44000}
                          />`
to assert that the same amount isn't suggested twice when the `minSendable` and `maxSendable` values are close to each other.

I also ran test e2e and unit tests:
- all e2e passed, except 2 skipped
- for unit tests:  Test Suites: 32 failed, 14 passed, 46 total ; Tests:  21 passed, 21 total (which is exactly the same as when running tests on the master of Alby even before any change).

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

2022-11-02 12:13 UTC, bitcoinuser commented
Hi, In my opinion would be better show only two buttons with the min and max values. Something like what Zebedee wallet does:
![Screenshot_2022-11-02-09-06-16-663_io zebedee wallet](https://user-images.githubusercontent.com/1178856/199486871-5d4f02d8-ceb3-45db-be11-3bac80b4fa14.jpg)

2022-11-02 12:16 UTC, bitcoinuser commented
Or maybe show an message if the user type an amount less the minimum or more than maximum. Not only disable the confirm button.

2022-11-02 13:49 UTC, bitcoinuser commented
I think inside the amount field should be empty and have text like: Send between x amount and y amount.

2022-11-02 14:11 UTC, fanismichalakis commented
Thanks @bitcoinuser for your comments!
 
> Hi, In my opinion would be better show only two buttons with the min and max values. Something like what Zebedee wallet does

I guess the "best solution" depends on what people use Alby for. What I like about the 100, 1K, 5K et 10K suggested values that are in place right now is that it makes perfect sense (at least to me) for tipping, Value4Value, etc. That's why I went for amounts that stayed quite close to this values, while taking the `minSendable` and `maxSendable` values into account.

> Or maybe show a message if the user type an amount less the minimum or more than maximum. Not only disable the confirm button.

I agree. I noticed that there already is a help text displayed when hovering on the input that does just that, although I think that it would be better to display it under the input field.

> I think inside the amount field should have a text like: Send between x sats and y sats.
Obs. The amount field should have no prefilled amount.

I think I prefer a prefilled amount (makes less clicks and helps decision, hence reducing transaction friction). Like for the help text on hover, I decided to let it like it was and focus on the `SatButtons` component. Happy to discuss it further and see what people think! :)

2022-11-06 07:52 UTC, reneaaron requested changes
Thanks for your contribution! I just tested the PR and noticed that the algorithm for creating the sats buttons creates some odd distribution for different min / max combinations.

I've prepared a list of LNURLs that we can use for testing here:
https://github.com/getAlby/lightning-browser-extension/wiki/%F0%9F%A4%A0-Alby-in-the-wild

![image](https://user-images.githubusercontent.com/100827540/200159441-80ff06d0-5d4d-488c-a665-73fca51eee7e.png)

![image](https://user-images.githubusercontent.com/100827540/200159818-fe1030af-f6da-4876-b5e7-4965c474121f.png)

I think we should aim for the following behaviour: 
 - Minimum is never lower than `min`
 - Maximum is never higher than `max`
 - Have the steps between `min` & `max` distributed evenly (but rounded to a number that depends on the size of the available range)

2022-11-06 07:54 UTC, reneaaron commented on src/app/components/SatButtons/index.tsx
> +  return number < 1000 ? Math.round(number) : Math.floor(number / 1000) * 1000;
Probably it would make sense to add some unit tests for this behavior as well. 

cc @escapedcat

2022-11-06 16:35 UTC, escapedcat commented on src/app/components/SatButtons/index.tsx
> +  return number < 1000 ? Math.round(number) : Math.floor(number / 1000) * 1000;
Happy to help with unit-tests if wanted once this is fixed.

2022-12-02 14:07 UTC, escapedcat commented
Hey @fanismichalakis , should we finish this up or do you want to? I assume you're busy and that's understandable. Happy to jump in here!

2022-12-09 17:47 UTC, escapedcat commented
Alright, awesome. No worries. I just wanted to check in. Thanks fort your reply!

2022-12-21 13:29 UTC, escapedcat commented on src/app/components/SatButtons/index.tsx
> +function amountsArray(min: number, max: number) {
Looking at this is leaving afraid and confused :P  
Not sure how others feel. Is there a nice way to makes this easier to digest?

2023-03-11 14:48 UTC, bitcoinuser commented
Hi @reneaaron was this fixed by https://github.com/getAlby/lightning-browser-extension/pull/2152?

If yes, I think this issue can be closed.

2023-03-13 14:29 UTC, reneaaron commented
@fanismichalakis I think with #2152 we've found a elegant (and less complex) solution to this kind of issue. Thanks for your work on this issue. Although this PR hasn't been merged, it brought up some important improvements! 🙌

@bitcoinuser Yep, thanks for the hint!

2023-03-13 14:29 UTC, closed without merging