chore: call it alby account
getAlby/lightning-browser-extension pull request #2187
Opened 2023-03-09 13:42 UTC by bumi

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/318/224041914-b27ef9c0-f50a-4d91-aec2-bb28d0e21edf.png">

2023-03-09 13:54 UTC, stackingsaunter commented
I think we should be consistent with capitalisation, so I suggest always capitalise "Alby Account"

2023-03-09 13:55 UTC, stackingsaunter commented on src/i18n/locales/en/translation.json
>          "description": "Sign up or use your existing Alby account to get started with lightning payments in no time.",
capitalise Alby **A**ccount in the description as well

2023-03-09 13:56 UTC, stackingsaunter requested changes
capitalise Alby **A**ccount in the description as well

2023-03-10 13:36 UTC, reneaaron approved these changes

2023-03-10 14:55 UTC, stackingsaunter approved these changes

2023-03-10 16:40 UTC, merged