feat: change wording to 'passcode'
getAlby/lightning-browser-extension pull request #2420
Opened 2023-05-11 12:39 UTC by im-adithya

### Describe the changes you have made in this PR

Changes the unlock screenshot and the wording from "password" to "passcode" as an attempt to help users understand better than this is not related to their alby account's password.

### Link this PR to an issue [optional]

Fixes #2251 

### Type of change

(Remove other not matching type)

- `feat` or `chore`

### Screenshots of the changes [optional]

<p  style="display: flex; justify-content: center;">
<img width="29%" src="https://github.com/getAlby/lightning-browser-extension/assets/64399555/a97ac15b-b341-436a-9ceb-59bd9d4c9cc0">
<img width="70%" src="https://github.com/getAlby/lightning-browser-extension/assets/64399555/bda3ab93-5c86-4548-adf1-2b916e60ffa8">
</p>

### How has this been tested?

Manually

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

2023-05-12 11:36 UTC, im-adithya commented
@stackingsaunter should be good now!

2023-05-14 23:39 UTC, reneaaron commented on static/assets/images/unlock_passcode.png
Please optimize PNGs using some tool like tinypng. Lossless compression can save ~80% here.

2023-05-14 23:41 UTC, reneaaron requested changes
See comment above, other than that :ok_hand: 

tACK

2023-05-17 08:02 UTC, im-adithya commented
Done!

2023-05-17 08:02 UTC, im-adithya commented on static/assets/images/unlock_passcode.png
Done!

2023-05-17 13:40 UTC, reneaaron approved these changes

2023-05-17 13:40 UTC, merged