feat: add margins around navigation icons
getAlby/lightning-browser-extension pull request #2959
Opened 2023-12-22 12:28 UTC by pavanjoshi914

### Describe the changes you have made in this PR

fix headers navigation icons

### Link this PR to an issue [optional]

Fixes _#ISSUE-NUMBER_

### Type of change

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes [optional]
before:
![image](https://github.com/getAlby/lightning-browser-extension/assets/55848322/35a05289-8f2b-41ac-95e1-d32bab970974)
after:

![image](https://github.com/getAlby/lightning-browser-extension/assets/55848322/9e6ee9a1-1c35-4f37-a06c-5a355712fe34)

### Checklist

- [X] Self-review of changed code
- [X] Manual testing
- [X] Added automated tests where applicable
- [X] Update Docs & Guides
- For UI-related changes
- [X] Darkmode
- [X] Responsive layout

2023-12-26 05:13 UTC, pavanjoshi914 commented
@rolznz @reneaaron here i am thinking what we do about the heading. it's something like ```pavanjoshi2050@gmail.com/Account settings``` this is quite big. and breaks responsiveness on smaller screen. is there specific reason to include account name as well in headings?

2023-12-27 09:05 UTC, pavanjoshi914 commented
> @rolznz @reneaaron here i am thinking what we do about the heading. it's something like `pavanjoshi2050@gmail.com/Account settings` this is quite big. and breaks responsiveness on smaller screen. is there specific reason to include account name as well in headings?

new changes regarding the same:::

https://github.com/getAlby/lightning-browser-extension/assets/55848322/22041077-ad0e-4bac-b57f-5a9c28aa803b

2024-01-30 22:58 UTC, reneaaron requested changes

2024-01-30 22:58 UTC, reneaaron commented on src/app/components/Avatar/index.tsx
> +        flexShrink: 0,
Move this to classNames.

2024-01-30 22:58 UTC, reneaaron commented on src/app/components/Avatar/index.tsx
> +        "rounded-full overflow-hidden translate-z-0 flex-shrink-0",
Isn't that just `shrink-0`? https://tailwindcss.com/docs/flex-shrink

2024-01-31 06:36 UTC, pavanjoshi914 commented on src/app/components/Avatar/index.tsx
> +        flexShrink: 0,
resolved

2024-01-31 10:06 UTC, reneaaron approved these changes
tACK

2024-01-31 10:06 UTC, merged