[chore] Update StartOS Brand
getAlby/lightning-browser-extension pull request #2974
Opened 2023-12-29 21:06 UTC by kn0wmad

### Describe the changes you have made in this PR

Updated branding/language for StartOS

### Type of change

- `fix`: branding

### How has this been tested?

Tested via Firefox debugging tool

### Checklist

- [] Self-review of changed code
- [ ] Manual testing
- [ ] Added automated tests where applicable
- [ ] Update Docs & Guides
- For UI-related changes
- [ ] Darkmode
- [ ] Responsive layout

2023-12-30 11:52 UTC, reneaaron requested changes
Thanks for the PR, looks good! :muscle: 

Let's update the logo and :shipit:

2023-12-30 11:52 UTC, reneaaron commented on static/assets/icons/startos.png
I'd heavily recommend adding some margin to the inner part of this logo to maintain some whitespace around it.

2024-01-02 16:34 UTC, kn0wmad commented on static/assets/icons/startos.png
Fixed, ready for re-review

2024-01-04 15:41 UTC, reneaaron approved these changes
tACK

2024-01-04 20:14 UTC, merged