feat: custom locale switcher
getAlby/lightning-browser-extension pull request #2981
Opened 2024-01-03 07:07 UTC by pavanjoshi914

### Describe the changes you have made in this PR

local switcher in onboardings screen
custom design to use it diffferent places 

### Link this PR to an issue [optional]

Fixes  #2918

### Type of change

(Remove other not matching type)

- `feat`: New feature (non-breaking change which adds functionality)

### Screenshots of the changes [optional]

![image](https://github.com/getAlby/lightning-browser-extension/assets/55848322/c257b596-4afa-41fc-8309-aea1f850dbf1)

### Checklist

- [X] Self-review of changed code
- [X] Manual testing
- [X] Added automated tests where applicable
- [X] Update Docs & Guides
- For UI-related changes
- [X] Darkmode
- [X] Responsive layout

2024-01-17 22:08 UTC, reneaaron requested changes

2024-01-18 10:35 UTC, pavanjoshi914 commented on src/app/router/Welcome/Welcome.tsx
> +        <div className="absolute top-0 left-0 mt-4 ml-6 z-50">
![image](https://github.com/getAlby/lightning-browser-extension/assets/55848322/3f81a953-0a8c-4a1d-87f2-874c912ef487)
![image](https://github.com/getAlby/lightning-browser-extension/assets/55848322/9248d181-c102-4783-86a8-83cd97c6b120)

2024-01-18 10:53 UTC, pavanjoshi914 commented
true absolute positioning was a bad idea there. cause even if we scroll switcher will be visible and designs are not like that to support this. i changed layout with something else

2024-01-18 11:00 UTC, stackingsaunter commented
Can't test without built but tACK

2024-01-22 10:10 UTC, reneaaron requested changes
Now the layout exceeds the window height and I see scrollbars (although there shouldn't be any).

2024-01-23 07:13 UTC, pavanjoshi914 commented
> Now the layout exceeds the window height and I see scrollbars (although there shouldn't be any).

I am unclear about the behavior we want to achieve here! it really depends on the content as well right? for eg. if i surf extension in brasil lang i can see scrollbars. as text there is longer.

locale switcher takes addditional space. even we adjust some content for en lang on other contents there will be still the scrollbars appearing

2024-01-23 07:17 UTC, pavanjoshi914 commented
https://github.com/getAlby/lightning-browser-extension/assets/55848322/b94fb3ad-f18f-441a-ba6f-ff45edd21cdf

2024-01-24 10:30 UTC, reneaaron commented
Sorry, I should have added a screenshot. The fullscreen page now always has scrollbars since the content of the page exceeds the available height. 

![image](https://github.com/getAlby/lightning-browser-extension/assets/100827540/5df79d7a-bb6b-4277-b350-d0a368a9ee16)

2024-01-30 22:07 UTC, reneaaron approved these changes
tACK

2024-01-30 22:08 UTC, merged