Feedback button
getAlby/lightning-browser-extension pull request #450
Opened 2021-12-06 17:49 UTC by secondl1ght

I added a feedback button to the popup menu and to the navbar. I also created a feedback component which currently just says 'Thank you for providing feedback to Alby!' but can be updated in the future to have an embedded feedback form. This was my first time using React Router and I just went off the current code as an example, I have been meaning to take a course on it so if I did anything wrong there just let me know. Both buttons open a new tab to: https://feedback.getalby.com

Screenshots:
![image](https://user-images.githubusercontent.com/85003930/144895907-dea26135-e283-447e-8ca5-c767310fe44f.png)

![image](https://user-images.githubusercontent.com/85003930/144896013-bafc6906-0529-45bf-bb7e-9f4abb01711a.png)

2021-12-13 16:25 UTC, bumi requested changes
I would say let's merge it with the link only in the menu (and not on the options screen) 
when we know what exactly we show on that Feedback component we can add it again.

2021-12-13 16:25 UTC, bumi commented on src/app/components/UserMenu/index.tsx
> +            window.open("https://feedback.getalby.com");
you can use `utils.openUrl` here: https://github.com/getAlby/lightning-browser-extension/blob/00c03bf895a295b90813de1b68d73f05959ea4f0/src/common/lib/utils.ts#L90

2021-12-14 00:19 UTC, secondl1ght commented
Sounds good, should I update this PR with only the changes you want for now?

2021-12-14 11:04 UTC, bumi commented
yeah, let's do that, then we ship this one

2021-12-15 05:13 UTC, secondl1ght commented
Ok sounds good, I have updated this PR so that only the feedback button in the popup menu is included currently.

I stashed my other edits in a new branch so we can pull them back in later if we want.

2021-12-15 11:02 UTC, bumi approved these changes
👍 perfect.

2021-12-15 11:02 UTC, merged