Show new account immediately in account list
getAlby/lightning-browser-extension pull request #592
Opened 2022-02-08 12:20 UTC by dylancom

Fixes #591

2022-02-08 12:45 UTC, dylancom commented
I'm not so sure about the new "AccountInfo" type. Do you maybe have an idea here @bumi? It was confusing that we had an Account type in state and  a different Account type in our AuthContext.

2022-02-10 14:52 UTC, bumi commented
@MoritzKa can you test this and confirm?

2022-02-10 14:57 UTC, bumi requested changes

2022-02-10 14:58 UTC, bumi commented
yes, we have to be careful about the naming here, right? it kinda is confusing. AccountInfo holds mainly the response from  the getInfo calls whereas the Account describes the account itself?

2022-02-10 15:19 UTC, MoritzKa commented
Worked well on Firefox. I couldn't test Chrome so easily, because somehow I cannot upload the zip packages from the Build files to  chrome://extensions/ anymore.

2022-02-10 15:29 UTC, bumi commented
@MoritzKa thanks. do you have the "developer mode" enabled? (top right corner)

2022-02-14 12:46 UTC, dylancom commented on src/app/screens/Options/TestConnection/index.tsx
> +      auth.setAccountId(currentAccountId);
Well at this point accountId is already set in state.ts but our ContextProvider used in the front-end app is not aware of the latest accountid. If it fails then setAccountInfo won't we called within this screen and the balance / info won't we updated within the front-end app.

2022-02-14 13:19 UTC, merged