feat: add RaspiBlitz
getAlby/lightning-browser-extension pull request #777
Opened 2022-04-05 21:13 UTC by secondl1ght

New PR for #683 due to merge conflicts.

2022-04-12 19:20 UTC, bumi requested changes
I did not look in detail, but I think this is not following the new connector screen refactorings: 

https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/connectors/ConnectMyNode/index.tsx#L91-L92

2022-04-12 19:20 UTC, bumi commented on src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
> +    if (event.target.value.substring(0, 4) !== "http") {
you should use `url` here, too.

2022-04-14 00:29 UTC, secondl1ght commented
> I did not look in detail, but I think this is not following the new connector screen refactorings:
> 
> https://github.com/getAlby/lightning-browser-extension/blob/master/src/app/screens/connectors/ConnectMyNode/index.tsx#L91-L92

Ok I updated this to use the new `ConnectorForm` component. Thanks for pointing that out I didn't notice we had a new component for this.

2022-04-14 01:20 UTC, bumi reviewed
ok, great. did you test it? did you also try to type the URL manually? 

@MoritzKa can you test again?

2022-04-14 02:47 UTC, secondl1ght commented
> ok, great. did you test it? did you also try to type the URL manually?
> 
> @MoritzKa can you test again?

Yep I tested it and was able to connect an LND node coming from Polar, I tried typing `http` and leaving it empty and it worked both times.

2022-04-14 02:52 UTC, bumi commented
great,thanks!

2022-04-20 06:50 UTC, MoritzKa commented
ACK 
https://onion_address works
onion_address works
http://onion_address does not work

2022-04-21 18:16 UTC, bumi commented
what does that mean? 
should the http:// address work? what means it does not work? what's the error?

2022-04-21 18:35 UTC, MoritzKa commented
for me `http://` does not need to work in order to merge this PR. 
I am reporting this because sendl1ght mention above that he "tried typing `http` and leaving it empty and it worked both times." I guess he meant `https`
I think the error message was "you are trying to call a HTTPS URI from a HTTP client"

2022-04-21 19:54 UTC, bumi approved these changes
utACK

2022-04-21 19:55 UTC, merged

2022-04-22 07:54 UTC, dylancom commented on src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
> +import ConnectorForm from "../../../components/ConnectorForm";
```suggestion
import ConnectorForm from "@components/ConnectorForm";
```

2022-04-22 07:54 UTC, dylancom commented on src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
> +import CompanionDownloadInfo from "../../../components/CompanionDownloadInfo";
```suggestion
import CompanionDownloadInfo from "@components/CompanionDownloadInfo";
```

2022-04-22 07:54 UTC, dylancom commented on src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
> +import TextField from "../../../components/form/TextField";
import TextField from "@components/form/TextField";

2022-04-22 07:55 UTC, dylancom commented on src/app/screens/connectors/ConnectRaspiBlitz/index.tsx
> +import utils from "../../../../common/lib/utils";
```suggestion
import utils from "~/common/lib/utils";
```

2022-04-22 14:50 UTC, bumi commented
@secondl1ght can you make a PR with those updated import paths?

2022-04-22 15:50 UTC, secondl1ght commented
Ok @dylancom is this a new way we are doing imports?

2022-04-22 17:19 UTC, bumi commented
> Ok @dylancom is this a new way we are doing imports?

https://github.com/getAlby/lightning-browser-extension/pull/798