fix: highlight selected account in menu
getAlby/lightning-browser-extension pull request #991
Opened 2022-06-03 17:44 UTC by im-adithya

### Describe the changes you have made in this PR

I have added a `selected` prop (as active is already in use because of Headless UI) to highlight the selected button in menu.

### Link this PR to an issue

### Type of change (Remove other not matching type)

- `fix`: Bug fix (non-breaking change which fixes an issue)

### Screenshots of the changes (If any)
![Screenshot from 2022-06-03 23-07-14](https://user-images.githubusercontent.com/64399555/171917223-6530bda4-0301-4eac-a904-dcb0cd906203.png)

### Note

Do we have to update the stories to include the new selected prop? 
(`/src/app/components/Menu/Menu.stories.tsx`)

### Checklist

- [x] My code follows the style guidelines of this project and performed a self-review of my own code
- [x] New and existing tests pass locally with my changes
- [x] I checked if I need to make corresponding changes to the documentation (and made those changes if needed)

2022-06-04 06:17 UTC, escapedcat requested changes

2022-06-04 06:17 UTC, escapedcat commented on src/app/components/AccountMenu/index.tsx
> +                selected={accountId === auth.account?.id}
Would you mind extending this test with the new `selected` prop?:  
https://github.com/getAlby/lightning-browser-extension/blob/ed6bb1aa3ae39ed674abc8f686fb3f64ef867541/src/app/components/AccountMenu/index.test.tsx  

i.e. add a test "Current account is being highlighted"

2022-06-04 06:19 UTC, escapedcat commented
In general I'm always a bit conflicted using `bold` for highlights because the text will be wider. If a text is already long this might break things. Not sure if this can be the case here though. Just a thing to keep in mind and maybe test it.

nit: Not sure if this a bugfix. It's more like a new feature I think.

Thanks for your work!

2022-06-04 08:41 UTC, im-adithya commented
> Would you mind extending this test with the new selected prop?:

Done! :D

> nit: Not sure if this a bugfix. It's more like a new feature I think.

Changed the commit message and title!

2022-06-04 09:40 UTC, im-adithya commented
Also we should wait for #992 to be merged so that I can change it here as well!
(i.e. `fireEvent` to `userEvent`)

2022-06-04 10:01 UTC, im-adithya commented
> so that I can change it here as well! (i.e. `fireEvent` to `userEvent`)

Done!

2022-06-04 13:52 UTC, bumi approved these changes
thanks! looks good to me. 
I think the bold can easily be changed when we maybe chat about the design with @dvoroneca

2022-06-05 03:37 UTC, escapedcat approved these changes

2022-06-05 03:38 UTC, merged

2022-06-07 07:53 UTC, escapedcat commented
@im-adithya fyi, @dylancom changed it a bit here to avoid changing "all" menus:  #1001